# SERP04: ¿Cuál es el estado actual de cada procedimiento administrativo?

PREFIX serpub: <http://vocab.linkeddata.es/datosabiertos/def/sector-publico/servicios-publicos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?procedimiento ?etiquetaProcedimiento ?estado
WHERE {
  ?procedimiento a serpub:AdministrativeProcedure ;
                 serpub:stateProcedure ?estado .

  OPTIONAL {
    ?procedimiento rdfs:label ?etiquetaProcedimiento .
    FILTER(LANG(?etiquetaProcedimiento) = "es")
  }
}
ORDER BY ?etiquetaProcedimiento